[package]
name = "mandelbrot_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
component = "0.1.0"
crate = "0.0.2"
num = "0.4.0"
